all: true
check-coverage: true
include: [src/**/*.js]
exclude:
  - src/assets/**
  - src/app/**/*[Ff]ields.js
  - src/app/**/steps.js
  - src/app/**/index.js
  - src/app.js
report-dir: reports/coverage
statements: 05
branches: 05
functions: 05
lines: 05
watermarks:
  statements:
    - 80
    - 90
  branches:
    - 80
    - 90
  functions:
    - 80
    - 90
  lines:
    - 80
    - 90
