# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        exclude: package-lock.json
      - id: check-case-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: .yarn
      - id: no-commit-to-branch
      - id: trailing-whitespace
        exclude: .yarn
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.55.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        args: ["."]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.83.3
    hooks:
      - id: cfn-lint
        files: .template\.ya?ml$
