name: Check PR

on: pull_request
permissions: {}

jobs:
  code-quality:
    name: Code quality
    uses: ./.github/workflows/code-quality.yml

  unit-tests:
    name: Run tests
    uses: ./.github/workflows/run-unit-tests.yml
    with:
      coverage-report: true

  browser-tests:
    name: Run tests
    uses: ./.github/workflows/run-browser-tests.yml

  deploy:
    name: Pre-merge deploy
    uses: ./.github/workflows/pre-merge-deploy.yml
    with:
      aws-region: eu-west-2
    secrets: inherit
