name: Post merge

on:
  push:
    branches: [main]

permissions:
  contents: read
  deployments: read
  id-token: write
  security-events: write

jobs:
  scan-and-unit-test:
    name: Scan repo
    uses: ./.github/workflows/scan-repo.yml

  deploy-dev:
    name: Package for dev
    needs: scan-and-unit-test
    uses: ./.github/workflows/post-merge-to-dev.yml

  deploy-build:
    name: Package for build
    needs: scan-and-unit-test
    uses: ./.github/workflows/post-merge-to-build.yml
