name: Unit tests

on:
  workflow_call:
    inputs:
      coverage-report: { type: boolean, required: false, default: false }
      coverage-artifact: { type: string, required: false, default: coverage }
    outputs:
      coverage-artifact:
        value: ${{ inputs.coverage-artifact }}

concurrency:
  group: unit-tests-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  run-tests:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        uses: govuk-one-login/github-actions/node/run-script@c8eefadf581d2087ce2af48b7060c1329cfa5251
        with:
          node-version: 20.x
          package-manager: npm
          script: npm run test:coverage

      - name: Archive coverage results
        if: ${{ inputs.coverage-report }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.coverage-artifact }}
          retention-days: 3
          path: reports/coverage/lcov.info
