name: Scan repository

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
  schedule:
    # Every Monday at 9am
    - cron: "0 9 * * 1"

concurrency:
  group: scan-repo-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: read-all

jobs:
  coverage:
    name: Collect coverage
    if: ${{ github.event_name != 'pull_request' }}
    uses: ./.github/workflows/run-unit-tests.yml
    with:
      coverage-report: true

  sonarcloud:
    name: SonarCloud
    needs: coverage
    runs-on: ubuntu-latest
    if: ${{ success() || needs.coverage.result == 'skipped' }}
    steps:
      - name: Run SonarCloud scan
        uses: govuk-one-login/github-actions/code-quality/sonarcloud@5480cced560e896dea12c47ea33e548a4d093e65
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-artifact: ${{ needs.coverage.outputs.coverage-artifact || 'coverage' }}
          coverage-run-id: ${{ github.event_name != 'pull_request' && github.run_id || null }}

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Run CodeQL scan
        uses: govuk-one-login/github-actions/code-quality/codeql@145049ebd9a33e57da9a852847c4ee2c8970ea51
        with:
          languages: javascript
